spring:
  datasource:
    url: jdbc:postgresql://dealer-db:5432/dealerdb
    username: dealer
    password: dealer123

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: dealer-service
